#	BSDI	Makefile,v 2.1 1995/02/03 06:51:55 polk Exp

LIB=	wrap
SRCS=	hosts_access.c options.c shell_cmd.c rfc931.c hosts_info.c \
	hosts_ctl.c refuse.c percent_x.c clean_exit.c \
	fromhost.c fix_options.c socket.c tli.c workarounds.c init_client.c \
	6compat.c
NOPROFILE=

.include "../Makefile.defs"

install:

.include <bsd.lib.mk>
