#	BSDI Makefile.inc,v 2.1 1995/02/03 06:29:19 polk Exp
#
#	@(#)Makefile.inc	8.1 (Berkeley) 6/4/93

SRCS+=	bcmp.s bcopy.s bzero.s ffs.c index.s memchr.s memcmp.s \
	memcpy.s memmove.s memset.s rindex.s strcat.s strchr.s \
	strcmp.s strcpy.s strcspn.c strlen.s strncat.s strncmp.s \
	strncpy.s strpbrk.c strrchr.s strsep.c strspn.c strstr.c
