#	BSDI	Makefile,v 2.1 1995/02/03 06:39:56 polk Exp

# NOTE: order of subdirs is important -- support must be first and 
#	ftpd must be second

SUBDIR=support ftpd ftpcount ftpshut

.include <bsd.subdir.mk>
