CC     = cc
AR     = ar cq
RANLIB = echo 
LIBC   = /lib/libc.a
IFLAGS = 
LFLAGS = 
CFLAGS = -O -DDEBUG ${IFLAGS} ${LFLAGS}

SRCS   = getusershell.c fnmatch.c strcasestr.c strsep.c
OBJS   = getusershell.o fnmatch.o strcasestr.o strsep.o

all: $(OBJS)
	-rm -f libsupport.a
	${AR} libsupport.a $(OBJS)
	${RANLIB} libsupport.a

clean:
	-rm -f *.o libsupport.a

ftp.h:
	install -c -m 444 ftp.h /usr/include/arpa

paths.h:
	install -c -m 444 paths.h /usr/include

fnmatch.o: fnmatch.c
	${CC} ${CFLAGS} -c fnmatch.c

getusershell.o: getusershell.c
	${CC} ${CFLAGS} -c getusershell.c

strcasestr.o: strcasestr.c
	${CC} ${CFLAGS} -c strcasestr.c

strsep.o: strsep.c
	${CC} ${CFLAGS} -c strsep.c
