.\" SCCSID: @(#)ftpcount.1   1.2 1/26/93
.TH ftpcount 1
.SH Name
ftpcount \- show current number of users for each class
.SH Syntax
.B ftpcount
.SH Description
.NXR "ftpcount command"
.NXR "system" "show ftpd usage"
The
.PN ftpcount
command
shows the current number of users (and the limit) for each
class defined in the ftpaccess file.
.PN ftpcount.
.SH See Also
ftpwho(1)
